GameId: "21847e8270334928af0feba4fc97b28c"
ClientVersion: "1.0.166-prod-s"
Name: "Craft Island (early alpha 0.1)"
Description: "Discord link: https://bit.ly/core-craft-island\r\no Farm\r\no Sell your items\r\no Decorate your island"
MaxPlayers: 8
Tags: "FirstPerson"
Tags: "Simulation"
Tags: "OpenWorld"
Tags: "Farming"
ScreenshotPaths: "C:\\Users\\hiind\\Desktop\\Craft.png"
ScreenshotPaths: "C:\\Users\\hiind\\Documents\\My Games\\CORE\\Saved\\Maps\\Craft Island\\Screenshots\\Screenshot0004.png"
ScreenshotPaths: "C:/Users/hiind/Documents/My Games/CORE/Saved/Maps/Craft Island/Screenshots/Screenshot0005.png"
OwnerId: "be87c969b2e5444dac5c09d330a142ab"
